server:
  port: 9000
application:
  name: "data-faker"
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    hibernate.ddl-auto: none
  flyway:
    sql-migration-prefix: V
    repeatable-sql-migration-prefix: R
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    locations: /db/migration
    enabled: true
    clean-on-validation-error: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  main:
    allow-bean-definition-overriding: true  


